#!/command/with-contenv bash

FLAGS=""

# configure `tailscale up`
if ! [ -v TAILSCALE_AUTH_KEY ]; then
    echo '[!] TAILSCALE_AUTH_KEY is not defined, this will print a login URL to the screen'
else
    FLAGS="${FLAGS} --authkey=${TAILSCALE_AUTH_KEY}"
fi

if [ -v TAILSCALE_HOSTNAME ]; then
    FLAGS="${FLAGS} --hostname=${TAILSCALE_HOSTNAME}"
fi

if [ -v TAILSCALE_SSH ]; then
    FLAGS="${FLAGS} --ssh=${TAILSCALE_SSH}"
fi

if [ -v TAILSCALE_EXIT_NODE ]; then
    echo '[!] acting as an exit node, you may need to approve this in the admin console'
    FLAGS="${FLAGS} --advertise-exit-node=${TAILSCALE_EXIT_NODE}"
fi

echo '[i] running `tailscale up '"${FLAGS}"'`'
tailscale up $FLAGS

# configure serve
if [ -v TAILSCALE_SERVE_PORT ]; then
    if [ "$TAILSCALE_FUNNEL" = "true" ]; then
        echo '[!] TAILSCALE_FUNNEL is enabled!'
        echo '[i] running `tailscale funnel -bg '"${TAILSCALE_SERVE_SOURCE_MODE:-http}"'://localhost:'"${TAILSCALE_SERVE_PORT}"'`'
        tailscale funnel -bg "${TAILSCALE_SERVE_SOURCE_MODE:-http}"://localhost:"${TAILSCALE_SERVE_PORT}"
    else
        echo '[!] TAILSCALE_FUNNEL is disabled!'
        echo '[i] running `tailscale serve -bg '"${TAILSCALE_SERVE_SOURCE_MODE:-http}"'://localhost:'"${TAILSCALE_SERVE_PORT}"'`'
        tailscale serve -bg "${TAILSCALE_SERVE_SOURCE_MODE:-http}"://localhost:"${TAILSCALE_SERVE_PORT}"
    fi
fi
