#!/command/with-contenv bash

FLAGS=""

# configure `tailscale up`
if ! [ -v TAILSCALE_AUTH_KEY ]; then
    echo '[!] TAILSCALE_AUTH_KEY is not defined, this will print a login URL to the screen'
else
    FLAGS="${FLAGS} --authkey=${TAILSCALE_AUTH_KEY}"
fi

if [ -v TAILSCALE_HOSTNAME ]; then
    FLAGS="${FLAGS} --hostname=${TAILSCALE_HOSTNAME}"
fi

if [ -v TAILSCALE_SSH ]; then
    FLAGS="${FLAGS} --ssh=true"
fi

if [ -v TAILSCALE_EXIT_NODE ]; then
    echo '[!] acting as an exit node, you may need to approve this in the admin console'
    FLAGS="${FLAGS} --advertise-exit-node=${TAILSCALE_EXIT_NODE}"
fi

echo '[i] running `tailscale up '"${FLAGS}"'`'
tailscale up $FLAGS

# configure serve
if [ -v TAILSCALE_SERVE_PORT ] && [ -v TAILSCALE_SERVE_MODE ] && [ -v TAILSCALE_SERVE_SOURCE_MODE ]; then
    echo '[i] running `tailscale serve '"${TAILSCALE_SERVE_MODE}"':443 / '"${TAILSCALE_SERVE_SOURCE_MODE}"'://localhost:'"${TAILSCALE_SERVE_PORT}"'`'
    tailscale serve "${TAILSCALE_SERVE_MODE}":443 / "${TAILSCALE_SERVE_SOURCE_MODE}"://localhost:"${TAILSCALE_SERVE_PORT}"
fi

# configure funnel
if [ -v TAILSCALE_FUNNEL ]; then
    echo '[i] running `tailscale funnel 443 on`'
    tailscale funnel 443 on
fi